name: Image CI Cache Cleaner

# Any change in triggers needs to be reflected in the concurrency group.
on:
  workflow_dispatch:
  schedule:
    # Run the GC every Monday at 6am
    - cron: "0 6 * * 1"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  cache-cleaner:
    name: Clean Image Cache
    runs-on: ubuntu-latest
    permissions:
      # `actions:write` permission is required to delete caches
      #   See also: https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
      actions: write
      contents: read
    steps:
      - name: Clean cache from GitHub
        shell: bash
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          set +e
          gh actions-cache delete ${{ runner.os }}-test-go-cache- -R $REPO -B main --confirm || true
          gh actions-cache delete ${{ runner.os }}-test-ccache- -R $REPO -B main --confirm || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
