name: Cilium CLI tests

on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'test/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-cilium-cli-binaries:
    name: Build Cilium CLI binaries
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.23.1

      # Load Golang cache build from GitHub
      - name: Load Golang cache build from GitHub
        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: go-cache
        with:
          path: /mnt/go/src/github.com/cilium/cilium/hack/cache/go
          key: ${{ runner.os }}-test-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-test-go-cache-

      - name: Create cache directories if they don't exist
        if: ${{ steps.go-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          sudo mkdir -p /mnt/go/src/github.com/cilium
          sudo chown $USER:$USER /mnt/go/src/github.com/cilium
          mkdir -p ./hack/cache/go/.cache/go-build
          mkdir -p ./hack/cache/go/pkg

      - name: Build hubble CLI release binaries
        env:
          GOCACHE: "/mnt/go/src/github.com/cilium/cilium/hack/cache/go/.cache/go-build"
          GOMODCACHE: "/mnt/go/src/github.com/cilium/cilium/hack/cache/go/pkg"
        run: |
          make -C cilium-cli local-release
